"use client";
import { useEffect,useMemo,useState } from "react";
import type { User } from "@supabase/supabase-js";
import { getSupabase } from "@/lib/supabase";
export default function AdminDashboard({user}:{user:User}){
 const supabase=useMemo(()=>getSupabase(),[]);const[profiles,setProfiles]=useState<any[]>([]);const[subs,setSubs]=useState<any[]>([]);const[orders,setOrders]=useState<any[]>([]);const[msg,setMsg]=useState("");
 async function load(){const[p,s,o]=await Promise.all([supabase.from("profiles").select("id,full_name,email,account_approved,created_at").order("created_at",{ascending:false}),supabase.from("subscriptions").select("user_id,status,membership_tiers(name,monthly_price_cents)"),supabase.from("fulfillment_orders").select("id,user_id,billing_cycle,delivery_due_date,status,skin_name,steam_trade_offer_id,internal_notes,profiles(full_name,email),membership_tiers(name),weapon_categories(name)").order("billing_cycle",{ascending:false})]);setProfiles(p.data||[]);setSubs(s.data||[]);setOrders(o.data||[])}
 useEffect(()=>{load()},[]);
 async function update(id:string,field:string,value:any){setMsg("Saving...");const payload: Record<string, unknown> = {[field]: value || null};const{error}=await (supabase.from("fulfillment_orders") as any).update(payload).eq("id",id);if(error)setMsg(error.message);else{setMsg("Saved.");await load()}}
 const sm=new Map(subs.map((s:any)=>[s.user_id,s]));
 return <main className="app-shell shell"><div className="dashboard-top"><div><p className="eyebrow">PRIVATE ADMIN</p><h1>Operations dashboard.</h1></div><a className="button secondary" href="/dashboard">Member view</a></div><div className="metrics"><article><small>MEMBERS</small><strong>{profiles.length}</strong><span>Registered accounts</span></article><article><small>ACTIVE SUBSCRIPTIONS</small><strong>{subs.filter((s:any)=>s.status==="active").length}</strong><span>Supabase records</span></article><article><small>OPEN ORDERS</small><strong>{orders.filter((o:any)=>!["accepted","completed"].includes(o.status)).length}</strong><span>Need attention</span></article><article><small>COMPLETED</small><strong>{orders.filter((o:any)=>["accepted","completed"].includes(o.status)).length}</strong><span>Historical count</span></article></div><section className="panel"><h2>Fulfillment queue</h2><p>Updates save to Supabase and appear in the member dashboard.</p>{orders.length?<div className="admin-orders">{orders.map((o:any)=><article className="admin-order" key={o.id}><div><small>MEMBER</small><strong>{o.profiles?.full_name||o.profiles?.email}</strong></div><div><small>CYCLE</small><strong>{o.billing_cycle}</strong></div><label>Status<select value={o.status} onChange={e=>update(o.id,"status",e.target.value)}>{["needs_assignment","needs_purchase","purchased","ready_to_send","trade_sent","accepted","completed","issue"].map(x=><option key={x}>{x}</option>)}</select></label><label>Skin<input defaultValue={o.skin_name||""} onBlur={e=>update(o.id,"skin_name",e.target.value)}/></label><label>Trade offer ID<input defaultValue={o.steam_trade_offer_id||""} onBlur={e=>update(o.id,"steam_trade_offer_id",e.target.value)}/></label><label>Internal notes<input defaultValue={o.internal_notes||""} onBlur={e=>update(o.id,"internal_notes",e.target.value)}/></label></article>)}</div>:<p className="empty-state">No fulfillment orders yet.</p>}{msg&&<p className="save-message">{msg}</p>}</section><section className="panel"><h2>Member directory</h2><div className="data-table"><div className="data-row head"><span>Member</span><span>Tier</span><span>Subscription</span><span>Approved</span></div>{profiles.map((p:any)=>{const s:any=sm.get(p.id);return <div className="data-row" key={p.id}><span>{p.full_name||p.email}</span><span>{s?.membership_tiers?.name||"None"}</span><span>{s?.status||"No subscription"}</span><span>{p.account_approved?"Yes":"No"}</span></div>})}</div></section></main>
}
